version: '3.8'

services:

  # ============================================================================================
  # [ BAZA DANYCH MYSQL ]
  # ============================================================================================
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - km-flask

  # ============================================================================================
  # [ BAZA DANYCH MYSQL FDO TESTOW ]
  # ============================================================================================
  mysql-test:
    image: mysql:latest
    volumes:
      - mysql-test:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - 3308
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - km-flask

  # ===================================================================================
  # [ APLIKACJA WEBOWA ]
  # ===================================================================================
  flask:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # gunicorn uruchomi 4 workers, ktore beda obslugiwaly requesty przychodzace
    # z nginx i wywolywaly create_app skonfigurowana w naszym projekcie

    # Dzieki --reload gunicorn przeladowuje automatycznie wszelkie zmiany w kodzie
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 'app.main:create_app()' --reload
    volumes:
      - ./:/webapp
    # Tutaj sprawdzamy, czy kontener mysql jest uruchomiony prawidlowo
    # To powoduje, ze kontener webapp moze normalnie ruszyc, kiedy kontener
    # mysql dziala prawidlowo
    # Jezeli tego nie zrobimy niestety nie dziala restartowanie kontenera
    # jezeli cos pojdzie nie tak - konfiguracja Django wymaga prawidlowej
    # pracy kontener mysql
    depends_on:
      mysql:
        condition: service_healthy
      mysql-test:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      # bardzo waznym jest nadanie w tym miejscu aliasu dla polaczenia ktore
      # w ramach sieci km-flask bedzie realizowane z kontenerem flask
      # ten alias jest pozniej wykorzystany w pliku konfiguracyjnym default.conf
      km-flask:
        aliases:
          - flask-app

  # ===================================================================================
  # KONFIGURACJA NGINX
  # ===================================================================================
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      # nginx korzysta z pliku konfiguracyjnego default.conf, ktory bedzie jednoczesnie
      # w specjalnej lokalizacji tak jak ponizej
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      # chcesz miec dostepny nginx na porcie 80
      - '80:80'
    depends_on:
      - flask
    networks:
      - km-flask
volumes:
  mysql:
  mysql-test:

networks:
  km-flask:

# Po tej konfiguracji
# [FLASK] <=== [8000] <=== [GUNCORN] <==(4 workers) <=== NGINEX [80]
